# Generated by Django 3.2.6 on 2021-09-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('rest', models.FloatField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reciever_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
