# Generated by Django 3.2.6 on 2021-09-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityOrganisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('organization', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=250)),
            ],
        ),
    ]
