# Generated by Django 3.2.6 on 2021-09-20 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_charityorganisations'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, upload_to='')),
                ('text', models.TextField()),
                ('charityorganisations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router.charityorganisations')),
            ],
        ),
    ]
